### ISSUE TITLE
LOHAS RGB + Tunable white

### ISSUE THREAD

**Issue by DarrenRatcliffe** [digiblur/ESPHome_LOHAS_LED#1]
Hi Travis,

I will get one of these delivered tomorrow [(https://www.amazon.co.uk/gp/product/B07LBQYLTH/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1)]

It might be a bit of a leap without you having one but how would you expect the ESP Home code to need to change for these?

Thanks

**Comment by digiblur** [comment]
Can't be that hard you'd think.  The channels might be mapped a bit differently but then again they might reuse the same LED driver board inside.  One easy way is not do the copying of channels yet, and just assign them to different channels and do the trial and error thing.  If you can pop the top that does make it much easier to see what is going on.

**Comment by lalank** [comment]
Wondering if there was any luck finding the mapping.  Picked these up without looking carefully:
https://www.amazon.com/gp/product/B07B3VNVVC.  Definitely not mapped the same.  Hint's to get started with _"One easy way is not do the copying of channels yet, and just assign them to different channels and do the trial and error thing"_ would be appreciated (like basic ESPhome yaml or Tasmota setup).  I have not gotten the hang of Tasmota and ESPhome yet; only hacked other's work so far.  So I just need pointed in the right direction.

BTW I bricked my test bulb with tuya-convert, and tried hard-wired programming.  Realized that the 3v3 pad on the control board (slightly different layout than in the video) was not connected!  I had to tie 3v3 from serial programmer to pin 8 of the memory chip to get it to flash.  Both Tasmota and ESPhome flashed, but mapping is really different.  The other pads were properly identified.  Not sure if that was a bad board via or an effort to throw off hardware hackers.

**Comment by digiblur** [comment]
If you have Tasmota on it you can try the Ailight and then just start trying different color channels by typing 

setoption17 1
then 
color 255,0,0,0
color 0,255,0,0
color 0,0,255,0

etc...

**Comment by ghost** [comment]
I'm working with these:  https://www.amazon.com/gp/product/B07B3VNVVC.

Good grief – you’re fast.  After I put the cover on the bulb, I got a whole different picture.  I actually tried what you suggested earlier, and got confused by the results.  I just deleted the original comment to clarify – been working on this too long and got blinded (almost literally).  But you responded too fast!  Sorry for the confusion.

With the white control full off, the brightness control adjusts the color brightness, and the color selection wheel works.  Your video setup works perfectly for the colors.

The difference is with the white channel; and I could not see it without diffusion.  The white control does not turn off the colors, but still controls brightness of the white, which washes out the colors.  That is best observed with the diffuser on.  With white full on, the brightness still controls the colors, so it just needs to be set low to turn off the colors.  The only thing I thought was missing appears to be the warmness channel.  This was not a mapping issue as I first thought; apparently I can't read - there is just a WW channel, not a CW channel.  Your video applies to these bulbs as well.  Awesome!

There was still the bricked bulb with tuya-convert, fixed by hardwired flashing.  That was probably my fault.  And the 3v3 pad on the only bulb I played with really was not connected -- pin 8 of the memory worked as the 3v3 pad and programming was not an issue after that.

Thank you for the rather exceptional videos (I’ve watched several).  I’ve been in the electronics industry for a long time (analog power designer half my career and now parts management).  You really are a good teacher!  Believe me, I’ve had a lot of them over nearly 40 years, so I appreciate your skill!  Thank you!

**Comment by digiblur** [comment]
Thanks!  I try to just break it down and teach how I would want someone to do the same in a video, I figure the pros can always fast forward through the stuff they know and the newbies can watch/listen.

Speaking of pictures do you have any pictures?  I noticed the description says daylight warm and I'm not even sure what that means as warm is one color and daylight is another.  Does it have two channels of cool white like mine did?  

Are you using Tasmota or Esphome with these bulbs?  I know there are two different templates to use with HA of one having the white attached and another the white is detached from the color, meaning as soon as you hit the white it shuts down the color LEDs, the attached mode blends the white with the color.  

Good work and thinking on the 3v3 of the memory flash!    

Waiting to hear back on the bulb LEDS, that would be awesome if they are WW and CW channels.

**Comment by ghost** [comment]
I’m using your ESPHome setup verbatim (except for the node name).  Thank you for that effort!  I’d never have figured it out and remained sane. 

 

Well I don’t feel as bad now – it seems you read the description the way I did.  I thought it was two channels, as well, until I pulled the cover to hardwire program the bulb.  The Lohas daylight warm is more mercury than sodium – It’s probably somewhere between CC and WW.  So unfortunately, it’s just one semi-warm white channel.

 

I included the templates in this response so there is no confusion.  I just grabbed the first thing I saw and used that.  Quite honestly, I had only just verified that ESP home was working on a Node MCU and wanted to try the bulb.  I Only have one of the three – my oldest got the other two for her apartment.

 

Thanks for the debugging compliment; it’s been a long time since I debugged hardware.  I was initially stumped with the serial programmer not working, but after I got into my debug mode it only took a couple of minutes to figure out. After I made sure nothing had happened with the USB-serial adapter (the cat has chewed on wires before), I disconnected the programmer and plugged the bulb into the mains.  A quick check with my hand-held DMM and all was clear.  You, see, instead of a paper route, I used to fix TV’s back when I was in 7th and 8th grade. The number one issue was power supplies (and dried up electrolytic caps), so the power source is where I usually start first.  Credit where due – my dad is still my teacher.  Of course, now he’s teaching me to age gracefully.  My last major professional hardware design has flown in space on GRO (Compton Observatory) and is now so many ions after NASA brought GRO down.  I designed the torque-rod drive electronics.  It was basically a programmable 3-channel current source with a zero-order hold to keep from applying step changes to the rather substantial torque rod inductance (~17 H at 3A).  Everything since then was small research oriented hardware.  I’ve been working with Space parts, counterfeit part detection and big (parts) data for the last 17 years.

 

I’m still fighting with ESPHome Dashboard.  There is some sort of websocket error (I think) and I can’t do anything in the dashboard but edit or I get a “Terminated Process” and several python errors.  I did everything via the command line.  Fortunately I learned on the command line ages ago on Radio Shack Model 1.  It’s scary how much DOS looks like Linux, at least from the command line.

 

It’ll be slow going – I’m still full time at a large aerospace company and I’m worn out by the time I get home.  If I discover anything new, I’ll keep in touch.  And keep those videos coming!

**Comment by digiblur** [comment]
Wow! That's awesome. Looks like only the 1 pack of lights is the 2 channel cool white. Makes me curious about their other bulbs now but I have bought enough bulbs. Way more than I need testing stuff. Ha.
