### ISSUE TITLE
Seperate White and Color Values broken in ESPHome v1.15.0

### ISSUE THREAD

**Issue by stenso** [digiblur/ESPHome_LOHAS_LED#6]
Upgraded Lohas Color bulbs to ESPHome v1.15, after upgrade the white and color values are no longer controlled separately. I was able to downgrade back to v1.14.5 to restore.

**Comment by digiblur** [comment]
Mine went wonky too... Finally forcing my hand to swap my last two over to Tasmota

**Comment by stenso** [comment]
Tasmota i great fir the newer RGBCCT bulbs. I did like using your ESPHome build for the older RGBW bulbs. Is there a way of achieving separate white value and color with Tasmota? If there is, I wouldn't be opposed to making the swap over too.

**Comment by digiblur** [comment]
SetOption68 | Multi-channel PWM instead of a single light0 = Treat PWM as a single light (default)1 = Treat PWM as separate channels. In this mode, use Power<x> to turn lights on and off, and Channel<x> to change the value of each channel.Color still works to set all channels at once.Requires restart after change
-- | --
